global:
  scrape_interval: 15s
  evaluation_interval: 15s
  # external_labels:
  #   monitor: "tf-serving-monitor"
 
 
scrape_configs:
  - job_name: "tensorflow-serving"
    scrape_interval: 5s 
    metrics_path: /monitoring/prometheus/metrics 
    static_configs:
      - targets: ['proyekakhir-production.up.railway.app'] 